# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrend.proto\x12\rgoogle_trends\"O\n\x0bGoogleTrend\x12.\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x1c.google_trends.GoogleArticle\x12\x10\n\x08keywords\x18\x02 \x03(\t\"<\n\rGoogleArticle\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x06source\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_sourceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trend_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GOOGLETREND']._serialized_start=30
  _globals['_GOOGLETREND']._serialized_end=109
  _globals['_GOOGLEARTICLE']._serialized_start=111
  _globals['_GOOGLEARTICLE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
